.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. expositio_qt test_expositio_qt
clean: FORCE
	$(MAKE) -C .. expositio_qt_clean test_expositio_qt_clean
check: FORCE
	$(MAKE) -C .. test_expositio_qt_check
expositio-qt expositio-qt.exe: FORCE
	 $(MAKE) -C .. expositio_qt
